// VORA — repères de Yaoundé.
//
// ══════════════════════════════════════════════════════════════════════════════
//  AVERTISSEMENT HONNÊTE SUR LES COORDONNÉES
//
//  Les latitudes et longitudes de ce fichier sont APPROXIMATIVES. Elles ont été
//  posées de mémoire et par recoupement cartographique, sans relevé GPS sur place :
//  comptez une erreur de 100 à 400 m selon les points. Elles suffisent à faire la
//  démonstration — chercher « ngoa », voir le repère tomber au bon endroit de la
//  carte, calculer un itinéraire crédible — et elles ne suffisent à rien d'autre.
//
//  Elles DEVRONT être corrigées sur le terrain avant tout usage réel : un point de
//  rendez-vous faux de 300 m, c'est le deuxième moment de vérité qui tombe (« le
//  chauffeur arrive comme promis », CLAUDE.md § 2).
//
//  C'est pourquoi chaque repère porte un `confidence` de 40 à 65 sur 100, jamais
//  davantage, et un `source: 'seed'` : la v1 laisse les chauffeurs corriger et
//  enrichir cette base, et un repère corrigé passera en `source: 'driver'` avec une
//  confiance plus haute. Le champ n'est pas décoratif, il est là pour être lu.
// ══════════════════════════════════════════════════════════════════════════════
//
//  `popularity` (0-100) est une estimation de la fréquence à laquelle un repère est
//  DEMANDÉ, pas de son importance. Le marché Mokolo est plus demandé que le musée
//  national, même si le musée est plus remarquable. C'est le dernier départage du tri
//  de recherche, derrière la similarité et la distance.
//
//  `aliases` porte les orthographes réelles des gens : sans accent, sans trait d'union,
//  avec le surnom local (« l'Immeuble de la Mort » pour le MINFI, « la Cathédrale »
//  pour Notre-Dame-des-Victoires). C'est ce qui fait qu'on trouve en tapant vite et mal.

export type LandmarkCategory =
  | 'carrefour'
  | 'marché'
  | 'quartier'
  | 'campus'
  | 'hôpital'
  | 'stade'
  | 'institution'
  | 'culte'
  | 'transport'
  | 'station'
  | 'hôtel'
  | 'poi';

export interface LandmarkSeed {
  name: string;
  aliases: string[];
  category: LandmarkCategory;
  district: string;
  lat: number;
  lng: number;
  /** 0-100 : à quelle fréquence ce repère est demandé. Départage final du tri. */
  popularity: number;
  /** 0-100 : fiabilité des coordonnées. Jamais plus de 65 pour une donnée non relevée. */
  confidence: number;
}

export const LANDMARK_SEED: LandmarkSeed[] = [
  // ─── Carrefours ────────────────────────────────────────────────────────────
  // Le repère par excellence à Yaoundé : on ne dit pas « 12 rue X », on dit
  // « dépose-moi au carrefour Warda ».
  {
    name: 'Carrefour Warda',
    aliases: ['Warda', 'Rond-point Warda', 'Carrefour Warda Bastos'],
    category: 'carrefour',
    district: 'Bastos',
    lat: 3.8797,
    lng: 11.5124,
    popularity: 92,
    confidence: 55,
  },
  {
    name: 'Carrefour Bastos',
    aliases: ['Bastos carrefour', 'Rond-point Bastos'],
    category: 'carrefour',
    district: 'Bastos',
    lat: 3.8908,
    lng: 11.5092,
    popularity: 84,
    confidence: 55,
  },
  {
    name: 'Carrefour Nlongkak',
    aliases: ['Nlongkak', 'Rond-point Nlongkak', 'Nlonkak'],
    category: 'carrefour',
    district: 'Nlongkak',
    lat: 3.8846,
    lng: 11.5179,
    popularity: 88,
    confidence: 55,
  },
  {
    name: 'Carrefour Elig-Essono',
    aliases: ['Elig Essono', 'Elig-Essono', 'Eligessono'],
    category: 'carrefour',
    district: 'Elig-Essono',
    lat: 3.8791,
    lng: 11.5232,
    popularity: 79,
    confidence: 50,
  },
  {
    name: 'Carrefour Ngoa-Ekellé',
    aliases: ['Ngoa Ekelle', 'Ngoa-Ekelle', 'Ngoa', 'Carrefour Ngoa'],
    category: 'carrefour',
    district: 'Ngoa-Ekellé',
    lat: 3.8564,
    lng: 11.5013,
    popularity: 83,
    confidence: 55,
  },
  {
    name: 'Carrefour Mvan',
    aliases: ['Mvan carrefour', 'Rond-point Mvan'],
    category: 'carrefour',
    district: 'Mvan',
    lat: 3.8181,
    lng: 11.5182,
    popularity: 86,
    confidence: 50,
  },
  {
    name: 'Carrefour Emana',
    aliases: ['Emana carrefour', 'Rond-point Emana'],
    category: 'carrefour',
    district: 'Emana',
    lat: 3.9366,
    lng: 11.5233,
    popularity: 72,
    confidence: 45,
  },
  {
    name: 'Carrefour Etoudi',
    aliases: ['Etoudi carrefour', 'Rond-point Etoudi'],
    category: 'carrefour',
    district: 'Etoudi',
    lat: 3.9092,
    lng: 11.5298,
    popularity: 74,
    confidence: 50,
  },
  {
    name: 'Carrefour Acacias',
    aliases: ['Acacias', 'Les Acacias', 'Carrefour Acacia'],
    category: 'carrefour',
    district: 'Mvog-Ada',
    lat: 3.8487,
    lng: 11.5236,
    popularity: 81,
    confidence: 50,
  },
  {
    name: 'Carrefour Obili',
    aliases: ['Obili', 'Rond-point Obili'],
    category: 'carrefour',
    district: 'Obili',
    lat: 3.8482,
    lng: 11.4931,
    popularity: 80,
    confidence: 50,
  },
  {
    name: 'Carrefour Melen',
    aliases: ['Melen carrefour', 'Rond-point Melen'],
    category: 'carrefour',
    district: 'Melen',
    lat: 3.8541,
    lng: 11.4872,
    popularity: 76,
    confidence: 50,
  },
  {
    name: 'Carrefour Mvog-Mbi',
    aliases: ['Mvog Mbi', 'Mvogmbi', 'Carrefour Mvogmbi'],
    category: 'carrefour',
    district: 'Mvog-Mbi',
    lat: 3.8563,
    lng: 11.5238,
    popularity: 82,
    confidence: 50,
  },
  {
    name: 'Carrefour Nsam',
    aliases: ['Nsam carrefour', 'Nsam Efoulan'],
    category: 'carrefour',
    district: 'Nsam',
    lat: 3.8294,
    lng: 11.5206,
    popularity: 73,
    confidence: 50,
  },
  {
    name: 'Carrefour Biyem-Assi',
    aliases: ['Biyem Assi', 'Biyemassi', 'Carrefour TAM', 'Biyem-Assi TAM'],
    category: 'carrefour',
    district: 'Biyem-Assi',
    lat: 3.8341,
    lng: 11.4784,
    popularity: 87,
    confidence: 50,
  },
  {
    name: 'Carrefour Ekounou',
    aliases: ['Ekounou', 'Ekounou carrefour'],
    category: 'carrefour',
    district: 'Ekounou',
    lat: 3.8287,
    lng: 11.5449,
    popularity: 68,
    confidence: 45,
  },
  {
    name: 'Carrefour Mimboman',
    aliases: ['Mimboman', 'Mimboman carrefour'],
    category: 'carrefour',
    district: 'Mimboman',
    lat: 3.8604,
    lng: 11.5487,
    popularity: 71,
    confidence: 45,
  },
  {
    name: 'Carrefour Nkolbisson',
    aliases: ['Nkolbisson carrefour', 'Nkol Bisson', 'Nkolbison'],
    category: 'carrefour',
    district: 'Nkolbisson',
    lat: 3.8663,
    lng: 11.4392,
    popularity: 70,
    confidence: 45,
  },
  {
    name: 'Carrefour Odza',
    aliases: ['Odza carrefour', 'Odza'],
    category: 'carrefour',
    district: 'Odza',
    lat: 3.8024,
    lng: 11.5391,
    popularity: 75,
    confidence: 45,
  },
  {
    name: 'Carrefour Damas',
    aliases: ['Damas', 'Damas carrefour'],
    category: 'carrefour',
    district: 'Damas',
    lat: 3.8338,
    lng: 11.5008,
    popularity: 69,
    confidence: 45,
  },
  {
    name: 'Carrefour Essos',
    aliases: ['Essos carrefour', 'Rond-point Essos'],
    category: 'carrefour',
    district: 'Essos',
    lat: 3.8768,
    lng: 11.5386,
    popularity: 78,
    confidence: 50,
  },
  {
    name: 'Carrefour Awae',
    aliases: ['Awae', 'Awae Escalier', "Carrefour Awae Escalier"],
    category: 'carrefour',
    district: 'Awae',
    lat: 3.8583,
    lng: 11.5418,
    popularity: 67,
    confidence: 45,
  },
  {
    name: 'Carrefour Nkolndongo',
    aliases: ['Nkolndongo', 'Nkol Ndongo', 'Nkoldongo'],
    category: 'carrefour',
    district: 'Nkolndongo',
    lat: 3.8692,
    lng: 11.5412,
    popularity: 70,
    confidence: 45,
  },
  {
    name: 'Carrefour Tsinga',
    aliases: ['Tsinga', 'Tsinga carrefour'],
    category: 'carrefour',
    district: 'Tsinga',
    lat: 3.8879,
    lng: 11.4984,
    popularity: 72,
    confidence: 45,
  },
  {
    name: 'Carrefour Etoa-Meki',
    aliases: ['Etoa Meki', 'Etoameki'],
    category: 'carrefour',
    district: 'Etoa-Meki',
    lat: 3.8827,
    lng: 11.5251,
    popularity: 66,
    confidence: 45,
  },
  {
    name: 'Carrefour Madagascar',
    aliases: ['Madagascar', 'Rond-point Madagascar'],
    category: 'carrefour',
    district: 'Madagascar',
    lat: 3.8718,
    lng: 11.5231,
    popularity: 74,
    confidence: 45,
  },
  {
    name: 'Carrefour Mokolo',
    aliases: ['Mokolo carrefour', 'Rond-point Mokolo'],
    category: 'carrefour',
    district: 'Mokolo',
    lat: 3.8759,
    lng: 11.5092,
    popularity: 79,
    confidence: 50,
  },
  {
    name: 'Carrefour Simbock',
    aliases: ['Simbock', 'Simbok'],
    category: 'carrefour',
    district: 'Simbock',
    lat: 3.8183,
    lng: 11.4779,
    popularity: 62,
    confidence: 40,
  },
  {
    name: 'Carrefour Ngousso',
    aliases: ['Ngousso', 'Ngousso carrefour'],
    category: 'carrefour',
    district: 'Ngousso',
    lat: 3.8931,
    lng: 11.5468,
    popularity: 69,
    confidence: 45,
  },
  {
    name: 'Carrefour Olembé',
    aliases: ['Olembe', 'Olembé', 'Olembe carrefour'],
    category: 'carrefour',
    district: 'Olembé',
    lat: 3.9539,
    lng: 11.5188,
    popularity: 64,
    confidence: 45,
  },
  {
    name: 'Carrefour Nkoabang',
    aliases: ['Nkoabang', 'Nkoabang carrefour'],
    category: 'carrefour',
    district: 'Nkoabang',
    lat: 3.8681,
    lng: 11.5967,
    popularity: 58,
    confidence: 40,
  },
  {
    name: 'Carrefour Golf',
    aliases: ['Golf', 'Rond-point Golf', 'Carrefour du Golf'],
    category: 'carrefour',
    district: 'Bastos',
    lat: 3.8887,
    lng: 11.5061,
    popularity: 71,
    confidence: 45,
  },
  {
    name: 'Carrefour Mvog-Betsi',
    aliases: ['Mvog Betsi', 'Mvogbetsi'],
    category: 'carrefour',
    district: 'Mvog-Betsi',
    lat: 3.8452,
    lng: 11.4938,
    popularity: 63,
    confidence: 40,
  },

  // ─── Marchés ───────────────────────────────────────────────────────────────
  {
    name: 'Marché Mokolo',
    aliases: ['Mokolo', 'Marche Mokolo', 'Grand marché Mokolo'],
    category: 'marché',
    district: 'Mokolo',
    lat: 3.8764,
    lng: 11.5086,
    popularity: 96,
    confidence: 55,
  },
  {
    name: 'Marché Central',
    aliases: ['Marche Central', 'Grand marché', 'Marché du Centre', 'Central Market'],
    category: 'marché',
    district: 'Centre-ville',
    lat: 3.8664,
    lng: 11.5183,
    popularity: 90,
    confidence: 55,
  },
  {
    name: 'Marché Mfoundi',
    aliases: ['Mfoundi', 'Marche Mfoundi', 'Marché du Mfoundi'],
    category: 'marché',
    district: 'Centre-ville',
    lat: 3.8621,
    lng: 11.5213,
    popularity: 85,
    confidence: 50,
  },
  {
    name: 'Marché Mvog-Mbi',
    aliases: ['Marche Mvog Mbi', 'Marché Mvogmbi'],
    category: 'marché',
    district: 'Mvog-Mbi',
    lat: 3.8571,
    lng: 11.5247,
    popularity: 77,
    confidence: 50,
  },
  {
    name: 'Marché Biyem-Assi',
    aliases: ['Marche Biyem Assi', 'Marché Biyemassi'],
    category: 'marché',
    district: 'Biyem-Assi',
    lat: 3.8322,
    lng: 11.4802,
    popularity: 83,
    confidence: 50,
  },
  {
    name: 'Marché Essos',
    aliases: ['Marche Essos', "Marché d'Essos"],
    category: 'marché',
    district: 'Essos',
    lat: 3.8757,
    lng: 11.5373,
    popularity: 79,
    confidence: 50,
  },
  {
    name: 'Marché Nkolndongo',
    aliases: ['Marche Nkolndongo', 'Marché Nkoldongo'],
    category: 'marché',
    district: 'Nkolndongo',
    lat: 3.8703,
    lng: 11.5431,
    popularity: 68,
    confidence: 45,
  },
  {
    name: 'Marché Etoudi',
    aliases: ['Marche Etoudi'],
    category: 'marché',
    district: 'Etoudi',
    lat: 3.9077,
    lng: 11.5312,
    popularity: 62,
    confidence: 45,
  },
  {
    name: 'Marché Madagascar',
    aliases: ['Marche Madagascar'],
    category: 'marché',
    district: 'Madagascar',
    lat: 3.8702,
    lng: 11.5243,
    popularity: 66,
    confidence: 45,
  },
  {
    name: 'Marché des Acacias',
    aliases: ['Marche Acacias', 'Marché Acacias'],
    category: 'marché',
    district: 'Mvog-Ada',
    lat: 3.8471,
    lng: 11.5244,
    popularity: 64,
    confidence: 45,
  },
  {
    name: 'Marché Mendong',
    aliases: ['Marche Mendong', 'Mendong marché'],
    category: 'marché',
    district: 'Mendong',
    lat: 3.8248,
    lng: 11.4652,
    popularity: 65,
    confidence: 40,
  },
  {
    name: 'Marché Elig-Edzoa',
    aliases: ['Elig Edzoa', 'Marche Elig Edzoa'],
    category: 'marché',
    district: 'Elig-Edzoa',
    lat: 3.8788,
    lng: 11.5309,
    popularity: 60,
    confidence: 40,
  },

  // ─── Universités et écoles ─────────────────────────────────────────────────
  {
    name: 'Université de Yaoundé I',
    aliases: ['UY1', 'Universite de Yaounde 1', 'Fac de Ngoa-Ekellé', 'Ngoa Ekelle fac'],
    category: 'campus',
    district: 'Ngoa-Ekellé',
    lat: 3.8629,
    lng: 11.5003,
    popularity: 91,
    confidence: 60,
  },
  {
    name: 'Université de Yaoundé II Soa',
    aliases: ['UY2', 'Fac de Soa', 'Universite de Soa', 'Soa'],
    category: 'campus',
    district: 'Soa',
    lat: 3.9773,
    lng: 11.5981,
    popularity: 73,
    confidence: 50,
  },
  {
    name: 'École Nationale Supérieure Polytechnique',
    aliases: ['ENSP', 'Polytechnique', 'Polytech Yaoundé', 'Ecole Polytechnique'],
    category: 'campus',
    district: 'Melen',
    lat: 3.8617,
    lng: 11.4929,
    popularity: 76,
    confidence: 55,
  },
  {
    name: 'École Normale Supérieure de Yaoundé',
    aliases: ['ENS', 'ENS Yaoundé', 'Ecole Normale'],
    category: 'campus',
    district: 'Ngoa-Ekellé',
    lat: 3.8646,
    lng: 11.5031,
    popularity: 70,
    confidence: 55,
  },
  {
    name: "École Normale Supérieure d'Enseignement Technique",
    aliases: ['ENSET', 'Enset Yaoundé', 'Ecole Normale Technique'],
    category: 'campus',
    district: 'Ngoa-Ekellé',
    lat: 3.8601,
    lng: 11.4996,
    popularity: 64,
    confidence: 45,
  },
  {
    name: "École Nationale d'Administration et de Magistrature",
    aliases: ['ENAM', 'Enam Yaoundé'],
    category: 'campus',
    district: 'Ekoudou',
    lat: 3.8724,
    lng: 11.5048,
    popularity: 68,
    confidence: 50,
  },
  {
    name: 'Institut des Relations Internationales du Cameroun',
    aliases: ['IRIC', 'Iric Yaoundé'],
    category: 'campus',
    district: 'Ngoa-Ekellé',
    lat: 3.8676,
    lng: 11.4972,
    popularity: 58,
    confidence: 45,
  },
  {
    name: 'ESSTIC',
    aliases: ['Esstic', 'École de journalisme', 'Ecole de journalisme'],
    category: 'campus',
    district: 'Ngoa-Ekellé',
    lat: 3.8634,
    lng: 11.4968,
    popularity: 57,
    confidence: 45,
  },
  {
    name: 'Université Catholique UCAC Nkolbisson',
    aliases: ['UCAC', 'Universite Catholique', 'Ucac Nkolbisson'],
    category: 'campus',
    district: 'Nkolbisson',
    lat: 3.8698,
    lng: 11.4404,
    popularity: 60,
    confidence: 45,
  },
  {
    name: 'Lycée Général Leclerc',
    aliases: ['Leclerc', 'Lycee General Leclerc', 'Lycée Leclerc'],
    category: 'campus',
    district: 'Nlongkak',
    lat: 3.8785,
    lng: 11.5052,
    popularity: 74,
    confidence: 50,
  },
  {
    name: 'Collège Vogt',
    aliases: ['Vogt', 'College Vogt'],
    category: 'campus',
    district: 'Mvolyé',
    lat: 3.8519,
    lng: 11.5093,
    popularity: 66,
    confidence: 45,
  },
  {
    name: "Lycée Bilingue d'Essos",
    aliases: ['Lycee Bilingue Essos', 'Bilingue Essos'],
    category: 'campus',
    district: 'Essos',
    lat: 3.8774,
    lng: 11.5403,
    popularity: 59,
    confidence: 40,
  },

  // ─── Hôpitaux ──────────────────────────────────────────────────────────────
  {
    name: 'Hôpital Central de Yaoundé',
    aliases: ['Hopital Central', 'HCY', 'Central hospital'],
    category: 'hôpital',
    district: 'Centre-ville',
    lat: 3.8723,
    lng: 11.5168,
    popularity: 89,
    confidence: 55,
  },
  {
    name: 'Hôpital Général de Yaoundé',
    aliases: ['Hopital General', 'HGY', 'Hôpital Général Ngousso'],
    category: 'hôpital',
    district: 'Ngousso',
    lat: 3.8961,
    lng: 11.5459,
    popularity: 84,
    confidence: 50,
  },
  {
    name: 'CHU de Yaoundé',
    aliases: ['CHU', 'Chu Melen', 'Centre Hospitalier Universitaire'],
    category: 'hôpital',
    district: 'Melen',
    lat: 3.8559,
    lng: 11.4903,
    popularity: 82,
    confidence: 50,
  },
  {
    name: 'Hôpital Gynéco-Obstétrique et Pédiatrique',
    aliases: ['HGOPY', 'Hopital Gyneco', 'Gynéco Ngousso'],
    category: 'hôpital',
    district: 'Ngousso',
    lat: 3.8934,
    lng: 11.5487,
    popularity: 72,
    confidence: 45,
  },
  {
    name: 'Hôpital Jamot',
    aliases: ['Hopital Jamot', 'Jamot'],
    category: 'hôpital',
    district: 'Elig-Edzoa',
    lat: 3.8759,
    lng: 11.5277,
    popularity: 70,
    confidence: 45,
  },
  {
    name: 'Hôpital de District de Biyem-Assi',
    aliases: ['Hopital Biyem Assi', 'District Biyem-Assi'],
    category: 'hôpital',
    district: 'Biyem-Assi',
    lat: 3.8331,
    lng: 11.4761,
    popularity: 67,
    confidence: 45,
  },
  {
    name: 'Centre Pasteur du Cameroun',
    aliases: ['Centre Pasteur', 'Pasteur'],
    category: 'hôpital',
    district: 'Centre-ville',
    lat: 3.8718,
    lng: 11.5121,
    popularity: 69,
    confidence: 50,
  },
  {
    name: 'Hôpital Militaire de Yaoundé',
    aliases: ['Hopital Militaire', 'HMR', 'Hôpital Militaire de Région'],
    category: 'hôpital',
    district: 'Nlongkak',
    lat: 3.8836,
    lng: 11.5148,
    popularity: 63,
    confidence: 45,
  },
  {
    name: 'Pharmacie de Melen',
    aliases: ['Pharmacie Melen', 'La pharmacie de Melen'],
    category: 'poi',
    district: 'Melen',
    lat: 3.8547,
    lng: 11.4884,
    popularity: 55,
    confidence: 40,
  },

  // ─── Stades ────────────────────────────────────────────────────────────────
  {
    name: 'Stade Omnisports Ahmadou Ahidjo',
    aliases: ['Stade Omnisports', 'Omnisports', 'Stade Ahidjo'],
    category: 'stade',
    district: 'Mfoundi',
    lat: 3.8651,
    lng: 11.5286,
    popularity: 88,
    confidence: 60,
  },
  {
    name: 'Stade Paul Biya Olembé',
    aliases: ['Stade Olembe', "Stade d'Olembé", 'Paul Biya stadium'],
    category: 'stade',
    district: 'Olembé',
    lat: 3.9641,
    lng: 11.5063,
    popularity: 80,
    confidence: 55,
  },
  {
    name: 'Stade Militaire de Yaoundé',
    aliases: ['Stade Militaire'],
    category: 'stade',
    district: 'Nlongkak',
    lat: 3.8792,
    lng: 11.5226,
    popularity: 58,
    confidence: 40,
  },

  // ─── Ministères et institutions ────────────────────────────────────────────
  {
    name: "Palais de l'Unité",
    aliases: ['Palais Etoudi', 'Palais présidentiel', "Palais de l'unite"],
    category: 'institution',
    district: 'Etoudi',
    lat: 3.9058,
    lng: 11.5347,
    popularity: 71,
    confidence: 55,
  },
  {
    name: 'Assemblée Nationale',
    aliases: ['Assemblee Nationale', "Palais de l'Assemblée", 'Ngoa Ekelle Assemblée'],
    category: 'institution',
    district: 'Centre-ville',
    lat: 3.8688,
    lng: 11.5218,
    popularity: 68,
    confidence: 50,
  },
  {
    name: 'Hôtel de Ville de Yaoundé',
    aliases: ['Hotel de Ville', 'Mairie de Yaoundé', 'Communauté urbaine'],
    category: 'institution',
    district: 'Centre-ville',
    lat: 3.8671,
    lng: 11.5163,
    popularity: 77,
    confidence: 55,
  },
  {
    name: 'Poste Centrale',
    aliases: ['La Poste', 'Poste centrale Yaoundé', 'Rond-point de la Poste'],
    category: 'institution',
    district: 'Centre-ville',
    lat: 3.8659,
    lng: 11.5171,
    popularity: 93,
    confidence: 55,
  },
  {
    name: 'Ministère des Finances',
    aliases: ['MINFI', 'Immeuble de la Mort', 'Ministere des Finances'],
    category: 'institution',
    district: 'Centre-ville',
    lat: 3.8672,
    lng: 11.5142,
    popularity: 72,
    confidence: 50,
  },
  {
    name: 'Ministère de la Santé Publique',
    aliases: ['MINSANTE', 'Ministere de la Sante'],
    category: 'institution',
    district: 'Centre-ville',
    lat: 3.8691,
    lng: 11.5133,
    popularity: 61,
    confidence: 45,
  },
  {
    name: 'Ministère des Relations Extérieures',
    aliases: ['MINREX', 'Ministere des Relations Exterieures'],
    category: 'institution',
    district: 'Centre-ville',
    lat: 3.8704,
    lng: 11.5156,
    popularity: 57,
    confidence: 45,
  },
  {
    name: 'Palais des Congrès',
    aliases: ['Palais des Congres', 'Congrès Yaoundé'],
    category: 'institution',
    district: 'Tsinga',
    lat: 3.8792,
    lng: 11.5094,
    popularity: 75,
    confidence: 50,
  },
  {
    name: 'Musée National du Cameroun',
    aliases: ['Musee National', 'Musée national'],
    category: 'institution',
    district: 'Centre-ville',
    lat: 3.8683,
    lng: 11.5152,
    popularity: 54,
    confidence: 45,
  },

  // ─── Lieux de culte ────────────────────────────────────────────────────────
  {
    name: 'Cathédrale Notre-Dame des Victoires',
    aliases: ['Cathedrale', 'La Cathédrale', 'Notre-Dame des Victoires'],
    category: 'culte',
    district: 'Centre-ville',
    lat: 3.8693,
    lng: 11.5179,
    popularity: 78,
    confidence: 55,
  },
  {
    name: 'Basilique Marie-Reine-des-Apôtres',
    aliases: ['Basilique Mvolye', 'Basilique de Mvolyé', 'Mvolye basilique'],
    category: 'culte',
    district: 'Mvolyé',
    lat: 3.8463,
    lng: 11.5058,
    popularity: 70,
    confidence: 50,
  },
  {
    name: 'Chapelle Nsimeyong',
    aliases: ['Nsimeyong chapelle', 'Chapelle de Nsimeyong'],
    category: 'culte',
    district: 'Nsimeyong',
    lat: 3.8381,
    lng: 11.4954,
    popularity: 56,
    confidence: 45,
  },
  {
    name: 'Grande Mosquée de Yaoundé',
    aliases: ['Grande Mosquee', 'Mosquée Briqueterie', 'Mosquee de la Briqueterie'],
    category: 'culte',
    district: 'Briqueterie',
    lat: 3.8801,
    lng: 11.5063,
    popularity: 68,
    confidence: 45,
  },

  // ─── Transport ─────────────────────────────────────────────────────────────
  {
    name: 'Aéroport International de Yaoundé-Nsimalen',
    aliases: ['Nsimalen', 'Aeroport Nsimalen', 'Aéroport', 'Airport Yaoundé'],
    category: 'transport',
    district: 'Nsimalen',
    lat: 3.7224,
    lng: 11.5532,
    popularity: 89,
    confidence: 65,
  },
  {
    name: 'Gare Voyageurs de Yaoundé',
    aliases: ['Gare de Yaoundé', 'Camrail', 'La gare', 'Gare ferroviaire'],
    category: 'transport',
    district: 'Elig-Essono',
    lat: 3.8608,
    lng: 11.5229,
    popularity: 81,
    confidence: 55,
  },
  {
    name: 'Gare routière de Mvan',
    aliases: ['Gare routiere Mvan', 'Agences de voyage Mvan', 'Mvan gare'],
    category: 'transport',
    district: 'Mvan',
    lat: 3.8203,
    lng: 11.5163,
    popularity: 79,
    confidence: 45,
  },
  {
    name: 'Station Total Mvan',
    aliases: ['Total Mvan', 'Station Mvan'],
    category: 'station',
    district: 'Mvan',
    lat: 3.8214,
    lng: 11.5171,
    popularity: 63,
    confidence: 45,
  },
  {
    name: 'Station Tradex Nlongkak',
    aliases: ['Tradex Nlongkak', 'Station Nlongkak'],
    category: 'station',
    district: 'Nlongkak',
    lat: 3.8853,
    lng: 11.5171,
    popularity: 58,
    confidence: 40,
  },

  // ─── Hôtels ────────────────────────────────────────────────────────────────
  {
    name: 'Hôtel Hilton Yaoundé',
    aliases: ['Hilton', 'Hotel Hilton'],
    category: 'hôtel',
    district: 'Centre-ville',
    lat: 3.8688,
    lng: 11.5149,
    popularity: 83,
    confidence: 60,
  },
  {
    name: 'Hôtel Mont Fébé',
    aliases: ['Mont Febe', 'Hotel Mont Febe', 'Mont Fébé'],
    category: 'hôtel',
    district: 'Mont Fébé',
    lat: 3.8938,
    lng: 11.4931,
    popularity: 72,
    confidence: 50,
  },
  {
    name: 'Yaoundé Djeuga Palace',
    aliases: ['Djeuga Palace', 'Djeuga'],
    category: 'hôtel',
    district: 'Centre-ville',
    lat: 3.8712,
    lng: 11.5188,
    popularity: 61,
    confidence: 45,
  },

  // ─── Quartiers ─────────────────────────────────────────────────────────────
  // Le quartier seul est une destination valable : « emmène-moi à Bastos » se dit
  // tous les jours. Le point est le centre approximatif du quartier.
  {
    name: 'Bastos',
    aliases: ['Quartier Bastos'],
    category: 'quartier',
    district: 'Bastos',
    lat: 3.8929,
    lng: 11.5104,
    popularity: 86,
    confidence: 50,
  },
  {
    name: 'Melen',
    aliases: ['Quartier Melen'],
    category: 'quartier',
    district: 'Melen',
    lat: 3.8553,
    lng: 11.4881,
    popularity: 78,
    confidence: 50,
  },
  {
    name: 'Obili',
    aliases: ['Quartier Obili'],
    category: 'quartier',
    district: 'Obili',
    lat: 3.8501,
    lng: 11.4918,
    popularity: 75,
    confidence: 50,
  },
  {
    name: 'Mvog-Ada',
    aliases: ['Mvog Ada', 'Mvogada', 'Quartier Mvog-Ada'],
    category: 'quartier',
    district: 'Mvog-Ada',
    lat: 3.8598,
    lng: 11.5318,
    popularity: 74,
    confidence: 45,
  },
  {
    name: 'Nkolbisson',
    aliases: ['Nkol Bisson', 'Quartier Nkolbisson'],
    category: 'quartier',
    district: 'Nkolbisson',
    lat: 3.8657,
    lng: 11.4381,
    popularity: 73,
    confidence: 45,
  },
  {
    name: 'Odza',
    aliases: ['Quartier Odza'],
    category: 'quartier',
    district: 'Odza',
    lat: 3.8061,
    lng: 11.5423,
    popularity: 76,
    confidence: 45,
  },
  {
    name: 'Nsam',
    aliases: ['Quartier Nsam'],
    category: 'quartier',
    district: 'Nsam',
    lat: 3.8302,
    lng: 11.5168,
    popularity: 71,
    confidence: 45,
  },
  {
    name: 'Mimboman',
    aliases: ['Quartier Mimboman'],
    category: 'quartier',
    district: 'Mimboman',
    lat: 3.8623,
    lng: 11.5538,
    popularity: 72,
    confidence: 45,
  },
  {
    name: 'Biyem-Assi',
    aliases: ['Biyem Assi', 'Biyemassi', 'Quartier Biyem-Assi'],
    category: 'quartier',
    district: 'Biyem-Assi',
    lat: 3.8334,
    lng: 11.4793,
    popularity: 85,
    confidence: 50,
  },
  {
    name: 'Ngoa-Ekellé',
    aliases: ['Ngoa Ekelle', 'Ngoa', 'Ngoa-Ekelle', 'Quartier Ngoa-Ekellé'],
    category: 'quartier',
    district: 'Ngoa-Ekellé',
    lat: 3.8581,
    lng: 11.5009,
    popularity: 80,
    confidence: 50,
  },
  {
    name: 'Essos',
    aliases: ['Quartier Essos'],
    category: 'quartier',
    district: 'Essos',
    lat: 3.8779,
    lng: 11.5392,
    popularity: 77,
    confidence: 45,
  },
  {
    name: 'Emana',
    aliases: ['Quartier Emana'],
    category: 'quartier',
    district: 'Emana',
    lat: 3.9331,
    lng: 11.5247,
    popularity: 69,
    confidence: 45,
  },
  {
    name: 'Etoudi',
    aliases: ['Quartier Etoudi'],
    category: 'quartier',
    district: 'Etoudi',
    lat: 3.9063,
    lng: 11.5303,
    popularity: 70,
    confidence: 45,
  },
  {
    name: 'Nsimeyong',
    aliases: ['Quartier Nsimeyong', 'Nsimeyon'],
    category: 'quartier',
    district: 'Nsimeyong',
    lat: 3.8384,
    lng: 11.4991,
    popularity: 68,
    confidence: 45,
  },
  {
    name: 'Efoulan',
    aliases: ['Quartier Efoulan'],
    category: 'quartier',
    district: 'Efoulan',
    lat: 3.8418,
    lng: 11.5103,
    popularity: 66,
    confidence: 45,
  },
  {
    name: 'Mendong',
    aliases: ['Quartier Mendong'],
    category: 'quartier',
    district: 'Mendong',
    lat: 3.8231,
    lng: 11.4668,
    popularity: 67,
    confidence: 40,
  },
  {
    name: 'Ekounou',
    aliases: ['Quartier Ekounou'],
    category: 'quartier',
    district: 'Ekounou',
    lat: 3.8279,
    lng: 11.5481,
    popularity: 65,
    confidence: 45,
  },
  {
    name: 'Tsinga',
    aliases: ['Quartier Tsinga'],
    category: 'quartier',
    district: 'Tsinga',
    lat: 3.8896,
    lng: 11.5003,
    popularity: 70,
    confidence: 45,
  },
  {
    name: 'Nlongkak',
    aliases: ['Nlonkak', 'Quartier Nlongkak'],
    category: 'quartier',
    district: 'Nlongkak',
    lat: 3.8852,
    lng: 11.5184,
    popularity: 79,
    confidence: 50,
  },
  {
    name: 'Elig-Essono',
    aliases: ['Elig Essono', 'Quartier Elig-Essono'],
    category: 'quartier',
    district: 'Elig-Essono',
    lat: 3.8802,
    lng: 11.5241,
    popularity: 72,
    confidence: 45,
  },
  {
    name: 'Mvan',
    aliases: ['Quartier Mvan'],
    category: 'quartier',
    district: 'Mvan',
    lat: 3.8186,
    lng: 11.5152,
    popularity: 78,
    confidence: 45,
  },
  {
    name: 'Ngousso',
    aliases: ['Quartier Ngousso'],
    category: 'quartier',
    district: 'Ngousso',
    lat: 3.8948,
    lng: 11.5479,
    popularity: 68,
    confidence: 45,
  },
  {
    name: 'Olembé',
    aliases: ['Olembe', 'Quartier Olembé'],
    category: 'quartier',
    district: 'Olembé',
    lat: 3.9503,
    lng: 11.5152,
    popularity: 64,
    confidence: 45,
  },
  {
    name: 'Mvolyé',
    aliases: ['Mvolye', 'Quartier Mvolyé'],
    category: 'quartier',
    district: 'Mvolyé',
    lat: 3.8479,
    lng: 11.5081,
    popularity: 63,
    confidence: 45,
  },
  {
    name: 'Cité Verte',
    aliases: ['Cite Verte', 'Quartier Cité Verte'],
    category: 'quartier',
    district: 'Cité Verte',
    lat: 3.8853,
    lng: 11.4898,
    popularity: 69,
    confidence: 45,
  },
  {
    name: 'Damas',
    aliases: ['Quartier Damas'],
    category: 'quartier',
    district: 'Damas',
    lat: 3.8342,
    lng: 11.5012,
    popularity: 66,
    confidence: 40,
  },
  {
    name: 'Mokolo',
    aliases: ['Quartier Mokolo'],
    category: 'quartier',
    district: 'Mokolo',
    lat: 3.8772,
    lng: 11.5088,
    popularity: 74,
    confidence: 45,
  },
  {
    name: 'Briqueterie',
    aliases: ['La Briqueterie', 'Quartier Briqueterie'],
    category: 'quartier',
    district: 'Briqueterie',
    lat: 3.8808,
    lng: 11.5074,
    popularity: 70,
    confidence: 45,
  },
  {
    name: 'Nkolndongo',
    aliases: ['Nkol Ndongo', 'Quartier Nkolndongo'],
    category: 'quartier',
    district: 'Nkolndongo',
    lat: 3.8687,
    lng: 11.5424,
    popularity: 67,
    confidence: 45,
  },
];

/** Utilisé par le seed et par les tests : le nombre de repères est un chiffre de démo. */
export const LANDMARK_SEED_COUNT = LANDMARK_SEED.length;
